### ISSUE TITLE
 Build Python SDK for HCX Participant System to help in integrating with HCX

### ISSUE THREAD

**Issue by shiva-rakshith** [Swasth-Digital-Health-Foundation/integration-sdks#51]
# Project Details

## What is HCX?

The Health Claim Exchange(HCX) Specification is a communication protocol that facilitates the exchange of health claim information between payers, providers, beneficiaries, and other relevant entities. It is designed to be an interoperable, machine-readable, auditable, verifiable, which helps ensure that the information being exchanged is accurate and trustworthy. It is an open standard based communication.

More details are [here](https://docs.swasth.app/hcx-specifications/)

## Features to be implemented
**Build a python SDK for integrator to integrate with HCX.** 

- Understanding [JSON Web Encryption](https://datatracker.ietf.org/doc/html/rfc7516)
- Parsing and validating incoming requests.
- Generating outgoing requests. 

**Current Scenario:** Currently, SDKs are available in [Java](https://github.com/Swasth-Digital-Health-Foundation/integration-sdks/tree/main/java/hcx-integrator-sdk) and [.Net](https://github.com/Swasth-Digital-Health-Foundation/integration-sdks/tree/main/dot-net).

**Acceptance Criteria:** A python SDK which will process the incoming and outgoing requests of the participant.

## Learning Path
**Complexity**
Medium

**Skills Required**
Python

**Name of Mentors**
@shiva-rakshith @saurabh-singh-17 @maheshkumargangula 

**Project size**
8 Weeks

## Milestones

- [ ] Understand HCX APIs
- [ ]  Build python SDK which will initialize participant configuration, processes requests received by the participants and generates  requests that need to be sent by the participant.

**Comment by MridulMohanta19** [comment]
I would like to work on this issue.

**Comment by prakharrathi25** [comment]
I am interested in this project. I am quite familiar with Python and it's related libraries and have contributed to open source projects using this tech stack. I would love to build the Python sdk for this project.

**Comment by Shetaanshu20** [comment]
This project looks really interesting! As a Python enthusiast, I'm excited about the opportunity to work with Python as the tech stack. I'd love to contribute to this project and learn from the team.

**Comment by UdAyAn123** [comment]
I am new to this stuffs but would love to contribute

**Comment by Ambitious-Anil** [comment]
Hi , I would like to contribute to this project as I am very familiar with Python and it seems very interesting to me .I am going to submit a proposal on this :)

**Comment by Wassaf001** [comment]
take me in.

**Comment by harshinirhsv** [comment]
Hi, I'm interested in this project. I have prior experience with python. I want to work on this issue and contribute to this project.

**Comment by Vaibss** [comment]
Hi could you please elaborate a little more process requests by participant i.e what type of data would be the input(an example would be helpful) and what type of response needs to be generated. Is it just parsing, validating and giving response or some kind of process automation?

**Comment by PandiKavya** [comment]
Hi, I'm interested in this project. I have knowledge in python.

**Comment by Tanishq5003** [comment]
Hi, I will be very excited to work with you

**Comment by PandiKavya** [comment]
I don't know how to work on this project. Can you give any information
about this project.

**Comment by priyanshi0720** [comment]
Hi, I'm interested in this project. It would be great to work on this project and bring in more creativeness and innovation to the idea.

**Comment by poojith7** [comment]
i am intrested in this project

**Comment by aanchallmittal** [comment]
I have prior experience in Python and I'm enthusiastic about joining this project. I'm eager to contribute my skills and knowledge to address the issues at hand and make a positive impact on the project.

**Comment by bhavp03** [comment]
I am fairly proficient in the language and would like to contribute to this issue. Please assign me this.

**Comment by sivaraju5609** [comment]
i have good knowledge in python skills i am very much intrested to contribute on this issue i will give my 100 percent on this project

**Comment by Himasnhu-AT** [comment]
Hi, I would like to contribute to this. May I know how can I get started? By the way, I'm also submitting it on C4GT. But I would love to contribute anyway.

Skills I Have: Python, different API working and integration into platforms.

**Comment by yash-0211** [comment]
Hello Sir,
I am currently in final year of BSc  from IIT Madras. I am proficient with python and have build web applications using python in past. I am really interested to work on this project using Python.
Please have a look at my most recent python project [link](https://github.com/yash-0211/BlogSite)

**Comment by shiva-rakshith** [comment]
Hi All,

Glad to hear that you are interested in contributing to this project. Please submit your proposal.

**Comment by Ansh-Srivastava-17** [comment]
hello sir,
being proficient in this programming language and also having built quite a few projects also I feel that this will be a great project for me to show my expertise.
Kindly allow me to contribute.
Also, could you explain what all problems are we facing with this so that I can mention it.

**Comment by sss2482** [comment]
Sir,
I am interested in this project and also I have very good experience in python programming. I think I can make a very good contribution to the project

**Comment by ARYASINGHBJC** [comment]
Hello sir, I possess strong proficiency in working with Python.  So I would love to work on this project. Please assign me and let me know how can I start working on this project.

**Comment by mehtapriya3105** [comment]
Hello sir, I have experience of working with almost 2 years in python, in different fields and hence have explored the language quite well. Hence I feel that I could be the right match for working in this project.

**Comment by Michael-G-Scott** [comment]
Hello sir. I have experience in integrating different products from one architecture to another. I have also experience in Python and Javascript. I am submitting my proposal and ideas for this project on c4gt since I feel this particular project has great potential to make an impact on society. It would be extremely kind of you to consider me for contributing to this project.

**Comment by ak2502** [comment]
Hi @shiva-rakshith, I am really interested in the project. Can you please elaborate on the acceptance criteria for C4GT. Do we need to build python SDK before selection or after selection. If not then please elaborate on the acceptance criteria to get selected for C4GT.

Thanks.

**Comment by jainendra001** [comment]
Hi @shiva-rakshith  ,

I'm Jainendra Tripathy, and I am interested in contributing to this project. I'm an AI and ML developer with good hands-on experience in Python.
I have a strong understanding of Python, and I'm always looking for new ways to learn and grow. I'm also a quick learner and always willing to help.
I'm available to contribute . I'm eager to get started and make a difference. I'm confident I can help you take this project to the next level.
If you're interested in having me contribute, please let me know. I'm happy to answer any questions you have.
And I am also applying to the C4GT too please consider my application.

Thanks,
Jainendra Tripathy

**Comment by anirudh34ag** [comment]
Hi @shiva-rakshith,  i am keen on contributing to this project. I am confident on my skills and i can work through the fundamental understanding of this project and establish good shape to it by achieving the milestones with greater efficiency.

**Comment by Inigojeevan** [comment]
@shiva-rakshith @saurabh-singh-17 @maheshkumargangula 
Dear Sir's
          I am interested to join and contribute in this project. I have required knowledge in python and i'm kinda a quick learner and I can adapt to new things!.

**Comment by VivekPrakashNitH** [comment]
@shiva-rakshith @saurabh-singh-17 @maheshkumargangula 
Respected Mentors,
 I am intrested in this project and I want to  contribute in this project. I am very much familiar with Pyhton and have build ML & AI  related projects for it  one of them is listed below :
https://github.com/VivekPrakashNitH/open-air-gym

**Comment by someshpradhan** [comment]
Dear Mentors,

I am writing to express my interest in the project . I am a freshy Python developer with experience in building SDKs and integrating with cloud-based systems. I am also familiar with the HCX Participant System and I am confident that I can contribute to this project.

**Comment by Atharva-214** [comment]
Sir, I would like to contribute to this. I have knowledge of python and have used its libraries for Image Processing, Deep learning projects. This would be a great opportunity for me. 
Looking forward in contributing to this.

**Comment by Srishti-j18** [comment]
Dear Mentors, I have submitted my proposal for the project  "Build Python SDK for HCX Participant System to help in integrating with HCX #51"..and looking forward to learn and contribute.
Thank you!!

**Comment by Darshan4852** [comment]
Dear Mentors,

I would like to express my strong interest in working on the Python SDK development project for integrating with the Health Claim Exchange (HCX) system. With my solid command over Data Structures and Algorithms (DSA) and proficiency in Python, I am confident in my ability to contribute effectively to this project. I am eager to learn the HCX APIs, design the SDK, and ensure seamless communication and data exchange between all participants. I would greatly appreciate the opportunity to work on this project.

Thank you for your consideration.

Sincerely,
Darshan Sharma

**Comment by VBHAVYASREE** [comment]
I would like to contribute to this. I have knowledge of python and have used its libraries for Image Processing, Deep learning projects. This would be a great opportunity for me.
Looking forward in contributing to this.
