### ISSUE TITLE
Build Javascript SDK for HCX Participant System to help in integrating with HCX

### ISSUE THREAD

**Issue by shiva-rakshith** [Swasth-Digital-Health-Foundation/integration-sdks#52]
# Project Details

## What is HCX?

The Health Claim Exchange(HCX) Specification is a communication protocol that facilitates the exchange of health claim information between payers, providers, beneficiaries, and other relevant entities. It is designed to be an interoperable, machine-readable, auditable, verifiable, which helps ensure that the information being exchanged is accurate and trustworthy. It is an open standard based communication.

More details are [here](https://docs.swasth.app/hcx-specifications/)

## Features to be implemented
**Build a JavaScript SDK for integrator to integrate with HCX.** 

- Understanding [JSON Web Encryption](https://datatracker.ietf.org/doc/html/rfc7516)
- Parsing and validating of incoming requests.
- Generating outgoing requests. 

**Current Scenario:** Currently, SDKs are available in [Java](https://github.com/Swasth-Digital-Health-Foundation/integration-sdks/tree/main/java/hcx-integrator-sdk) and [.Net](https://github.com/Swasth-Digital-Health-Foundation/integration-sdks/tree/main/dot-net).

**Acceptance Criteria:** A JavaScript SDK which will process the incoming and outgoing requests of the participant.

## Learning Path
**Complexity**
Medium

**Skills Required**
JavaScript

**Name of Mentors**
@shiva-rakshith @saurabh-singh-17 @AbhiGaddi  

**Project size**
8 Weeks

## Milestones

- [ ] Understand HCX APIs
- [ ]  Build JavaScript SDK which will initialize participant configuration, processes requests received by the participants and generates requests that need to be sent by the participant.

**Comment by Vinay2001k** [comment]
I want to work on this issue.

**Comment by SrijanShovit** [comment]
Hi mentors, I am interested in this project.

**Comment by prateek-10** [comment]
hello mentors, i want to be a part of this project

**Comment by achal-durden** [comment]
Hello mentors where is the repo link 
?

**Comment by shiva-rakshith** [comment]
> Hello mentors where is the repo link ?

HCX Platform: https://github.com/Swasth-Digital-Health-Foundation/hcx-platform
Java SDK: https://github.com/Swasth-Digital-Health-Foundation/integration-sdks

**Comment by Rijudas149** [comment]
Hello Mentors, I'm interested in this project

**Comment by shiva-rakshith** [comment]
> Hi @shiva-rakshith
> 
> I am thrilled to express my interest in contributing to the HCX project. The concept of the Health Claim Exchange (HCX) Specification and its goal of facilitating the secure exchange of health claim information has captured my attention. As a junior undergraduate student pursuing a degree in Computer Science and Engineering, I believe this project aligns perfectly with my interests and skills.
> 
> I would like to take on the challenge of building a JavaScript SDK for integrators to seamlessly integrate with HCX. With a strong foundation in JavaScript, I am confident in parsing and validating incoming requests, as well as generating outgoing requests. My experience in working with JSON Web Encryption further enhances my ability to contribute to this project.
> 
> I have previously contributed to open source programs, including being one of the top contributors in GSSoC'22. These experiences have honed my collaborative skills, project management abilities, and technical acumen.
> 
> I would appreciate your guidance on how to get started with the HCX project. I have started reading about HCX APIs. Should I directly submit my proposal, or is there any specific process I need to follow?
> 
> I am eager to dive into the work and make a meaningful contribution.
> 
> I look forward to collaborate with mentors and contribute to this project.
> 
> Best Regards, Sukriti Maurya

Hi @Sukriti-m, submit the proposal.

**Comment by utkars3** [comment]
Hello mentors @shiva-rakshith  I will be happy to work in this project. Can you tell me the resources which I should start study to tackle the issue

**Comment by Sankushe123** [comment]
Dear @shiva-rakshith,

I hope you are doing well. I am writing to express my keen interest in the project involving the development of a JavaScript SDK to initialize participant configurations, process requests received by participants, and generate requests that need to be sent. Additionally, I am eager to gain a comprehensive understanding of HCX APIs under your expert guidance.

I am excited about the opportunity to delve into HCX APIs. While I might not have direct experience with HCX APIs specifically, I am a fast learner and passionate about exploring new technologies. I have a solid understanding of RESTful API design principles, and I am confident that I can quickly grasp the concepts and intricacies of HCX APIs with your guidance.

I strongly believe that this project aligns perfectly with my skills, interests, and career goals. I am eager to take on the challenge of building the JavaScript SDK and gaining a deep understanding of HCX APIs under your mentorship. I am confident that this experience will not only enhance my technical proficiency but also contribute to my professional growth.

Thank you for considering my application. I would be delighted to discuss this project in more detail and answer any questions you may have. I look forward to the opportunity to work with you and contribute to the success of this endeavor.

Grateful Regards,
Shubham Ankushe

**Comment by Sankushe123** [comment]
Dear @shiva-rakshith,

I hope you are doing well. I am writing to express my keen interest in the project involving the development of a JavaScript SDK to initialize participant configurations, process requests received by participants, and generate requests that need to be sent. Additionally, I am eager to gain a comprehensive understanding of HCX APIs under your expert guidance.

I am excited about the opportunity to delve into HCX APIs. While I might not have direct experience with HCX APIs specifically, I am a fast learner and passionate about exploring new technologies. I have a solid understanding of RESTful API design principles, and I am confident that I can quickly grasp the concepts and intricacies of HCX APIs with your guidance.

I strongly believe that this project aligns perfectly with my skills, interests, and career goals. 

I am eager to take on the challenge of building the JavaScript SDK and gaining a deep understanding of HCX APIs under your mentorship. 

I am confident that this experience will not only enhance my technical proficiency but also contribute to my professional growth.

I look forward to collaborating with mentors and contributing to this project.

Thank you for considering my application. I would be delighted to discuss this project in more detail and answer any questions you may have. I look forward to the opportunity to work with you and contribute to the success of this endeavor.

Grateful Regards,
Shubham Ankushe

**Comment by Sankushe123** [comment]
Hello, @shiva-rakshith,

I hope you are doing well. I am writing to express my keen interest in the project involving the development of a JavaScript SDK to initialize participant configurations, process requests received by participants, and generate requests that need to be sent. Additionally, I am eager to gain a comprehensive understanding of HCX APIs under your expert guidance.

I am excited about the opportunity to delve into HCX APIs. While I might not have direct experience with HCX APIs specifically, I am a fast learner and passionate about exploring new technologies. I have a solid understanding of RESTful API design principles, and I am confident that I can quickly grasp the concepts and intricacies of HCX APIs with your guidance.

I strongly believe that this project aligns perfectly with my skills, interests, and career goals.

I am eager to take on the challenge of building the JavaScript SDK and gaining a deep understanding of HCX APIs under your mentorship.

I am confident that this experience will not only enhance my technical proficiency but also contribute to my professional growth.

I look forward to collaborating with mentors and contributing to this project.

Thank you for considering my application. I would be delighted to discuss this project in more detail and answer any questions you may have. I look forward to the opportunity to work with you and contribute to the success of this endeavor.

Grateful Regards,
Shubham Ankushe

**Comment by harshikagoyal14** [comment]
Hello @shiva-rakshith ,

I hope this message finds you well. I am writing to express my sincere interest in the project involving the development of a JavaScript SDK for participant configurations, request processing, and request generation within the HCX ecosystem. Furthermore, I am eager to expand my knowledge and understanding of HCX APIs with your expert guidance.

The opportunity to work with HCX APIs is truly captivating to me. Although I may not possess direct experience with HCX APIs, I am highly motivated to explore new technologies and quickly acquire the necessary skills. With a strong foundation in RESTful API design principles, I am confident in my ability to swiftly grasp the intricacies of HCX APIs under your mentorship.

I firmly believe that this project aligns perfectly with my skills, interests, and long-term career goals. The challenge of building a JavaScript SDK and gaining a comprehensive understanding of HCX APIs with your guidance is both exhilarating and rewarding. I am enthusiastic about the prospect of collaborating with you and making meaningful contributions to the success of the project.

I am confident that this experience will not only enhance my technical proficiency but also contribute significantly to my professional growth. I am eager to actively engage with mentors and work closely with the team to ensure the project's success.

Thank you for considering my application. I would welcome the opportunity to discuss this project further, address any questions or concerns you may have, and provide any additional information required. I am genuinely excited about the possibility of working together and making a valuable contribution to this endeavor.

Thank you for your time and consideration.

Best regards,
Harshika Goyal

**Comment by saketharshraj** [comment]
Hello @shiva-rakshith 
My name is Harsh Raj. I am a backend developer and loves solving real life problems using existing technology.

I am interested in this project. Can you please guide me with this project ?

Thanks

**Comment by FirePing32** [comment]
Hey team
I am Prakhar Gurunani, a pre-final year student at BITS Pilani. I have worked on a similar project in GSoC 2022. I am eager to contribute to this project. Looking forward to submitting a proposal soon 🚀

**Comment by sivaraju5609** [comment]
hello every one!
this is sivaraju i had a good knowledge on javascript code i am currently student in nxtwave ccbp 4.0 accadamy let give me a chance to contribute to this project i will give my best to this project

**Comment by shiva-rakshith** [comment]
> Hello mentors @shiva-rakshith I will be happy to work in this project. Can you tell me the resources which I should start study to tackle the issue

Hi @utkars3 
Go through the docs shared in the above article and understand about HCX and submit a proposal.

**Comment by shiva-rakshith** [comment]
Hi All,

Glad to hear that you are interested in contributing to this project. Please submit your proposal.

**Comment by ujjwalkirti** [comment]
@shiva-rakshith Hello sir,
We can start contributing to the above mentioned issue only after our proposal for the same is accepted under CodeforGovTech initiative?

**Comment by Ayan-thecodeking** [comment]
hey @shiva-rakshith 
I hope you are doing well. I'm excited to express my keen interest in contributing to this project. After conducting a comprehensive review of the issue details, discussions, and codebase, my skills and experience align well with the project requirements. I have prior experience working with React.js, JavaScript, and CSS, With my expertise in these technologies, I believe I can make valuable contributions to this project. I would greatly appreciate your guidance and support to ensure I can deliver my best work. 🙌 
I need to discuss something before applying to proposal , please let me know whenever you are available to connect in discord or meet ?

**Comment by anii-jain** [comment]
Hey @shiva-rakshith 

I am interested in contributing to this project. My name is Animesh Jain, and I'm an Undergrad at The LNM Institute of Information Technology. I have gone through the details and my knowledge of Javascript and other associated web technologies makes me well-suited to contribute. I also have pretty good knowledge of MERN stack development.

I am highly interested in participating in the project and want to contribute.

**Comment by FirePing32** [comment]
Hey @shiva-rakshith 
Do we have to build the SDK only for the Participant Registry APIs?
Or do we also have to include the HCX APIs in this SDK?

**Comment by abhigyan-aaa** [comment]
> Hi @shiva-rakshith
> 
> I am thrilled to express my interest in contributing to the HCX project. The concept of the Health Claim Exchange (HCX) Specification and its goal of facilitating the secure exchange of health claim information has captured my attention. As a junior undergraduate student pursuing a degree in Computer Science and Engineering, I believe this project aligns perfectly with my interests and skills.
> 
> I would like to take on the challenge of building a JavaScript SDK for integrators to seamlessly integrate with HCX. With a strong foundation in JavaScript, I am confident in parsing and validating incoming requests, as well as generating outgoing requests. My experience in working with JSON Web Encryption further enhances my ability to contribute to this project.
> 
> I have previously contributed to open source programs, including being one of the top contributors in GSSoC'22. These experiences have honed my collaborative skills, project management abilities, and technical acumen.
> 
> I would appreciate your guidance on how to get started with the HCX project. I have started reading about HCX APIs. Should I directly submit my proposal, or is there any specific process I need to follow?
> 
> I am eager to dive into the work and make a meaningful contribution.
> 
> I look forward to collaborate with mentors and contribute to this project.
> 
> Best Regards, Sukriti Maurya

did some efforts to change it a bit from chat gpt

**Comment by Aarav238** [comment]
Hey @shiva-rakshith , I am computer Science under grad . I am familiar with full stack Development(MERN), I also have knowledge of containerization and I also hands on experience with postman . I would love to contribute in this project and explore more in the community. Can you please guide me how to get started?

**Comment by SmritiV23** [comment]
Hi @shiva-rakshith,
I am delighted to express my enthusiasm for participating in the HCX project. Health Claim Exchange (HCX) Specification aims to facilitate the secure sharing of health claim information, has captured my interest. As an undergraduate student in Information Science and Engineering, I believe this project aligns perfectly with my interests and skills.

I would like to take on the challenge of building a JavaScript SDK for integrators to seamlessly integrate with HCX. With a strong foundation in JavaScript, I am confident in parsing and validating incoming requests, as well as generating outgoing requests. I have contributed to open source program like GirlScript Summer of Code. These experiences have honed my collaborative skills, project management abilities, and technical acumen.

I would greatly appreciate your guidance on how to begin my involvement in the HCX project. I have started familiarizing myself with HCX APIs.
I am looking forward to collaborate with mentors and contribute to this project.

Best Regards,
Smriti Verma

**Comment by dikshajaiswal855** [comment]
Hello @shiva-rakshith @saurabh-singh-17 @AbhiGaddi,
I am interested in this projest and I am looking forward to contribute to the project

**Comment by HarshPanchal26** [comment]
Hello ,  I am Harsh Panchal , currently a last year student , I go through project idea  and want to contribute for this , 
@shiva-rakshith  Can you please guide bit more us , about what framework or any thing required , Is there any code base to go through before create proposal ?

Thank You

**Comment by avantika09-del** [comment]
I am interested in this topic, can you please guide.
